import Head from "next/head";
import { ReactNode } from "react";
import { Box } from "@chakra-ui/react";

export const LayoutApp = ({
    title,
    children
}: {
    title: string,
    children: ReactNode | ReactNode[];
}) => {
    return (
        <Box bg={'white'} minH={'100vh'} maxW={'100vw'} overflow={'hidden'}>
            <Head>
                <title>{`${title} | Name Shop`}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <main>
                    {children}
                </main>
            </ div>
        </Box>
    )
}